In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [2]:
housing_df = pd.read_csv("combined_data_clean.csv")
housing_df.head()


id   Price              Address    zip  status      mls  \
0   1  427167  3231 W MARYLAND AVE  85017  Active  6395749   
1   2  400000     5109 E THOMAS RD  85018  Active  6243667   
2   3  399900    8020 W STELLA AVE  85303  Active  6384821   
3   4  349000      6944 W Verde LN  85033  Active  6395738   
4   5  419000  4105 W PASADENA AVE  85019  Active  6395732   

                Subdivision  Year Built  Bedrooms  Bathrooms  Approx SQFT  
0  WEST PLAZA 6 LOT 614-787        1958         3        2.0       1302.0  
1            PAPAGO VILLAGE        1943         0        0.0       1358.0  
2                  SHALIMAR        1997         3        2.0       1505.0  
3   MARYVALE TERRACE NO. 49        1983         3        3.0       1514.0  
4            TU-DOR ESTATES        1971         4        2.0       1908.0

In [3]:
education_df = pd.read_csv("education_by_zip.csv")
education_df.head()
education_df.rename(columns={'Zip':'zip'},inplace=True)
education_df.head()

zip Elem_School_District  Hightest_Rated_School
0  85003   Phoenix Elementary                  94.44
1  85004   Phoenix Elementary                  94.44
2  85006   Phoenix Elementary                  94.44
3  85007   Phoenix Elementary                  94.44
4  85008                Balsz                  81.79

In [4]:
housing_df.drop_duplicates()

id   Price               Address    zip  status      mls  \
0        1  427167   3231 W MARYLAND AVE  85017  Active  6395749   
1        2  400000      5109 E THOMAS RD  85018  Active  6243667   
2        3  399900     8020 W STELLA AVE  85303  Active  6384821   
3        4  349000       6944 W Verde LN  85033  Active  6395738   
4        5  419000   4105 W PASADENA AVE  85019  Active  6395732   
...    ...     ...                   ...    ...     ...      ...   
2260  2311  600000  3402 E CAROL ANN WAY  85032  Closed  6368329   
2261  2312  375000   739 E Constance WAY  85042  Closed  6358973   
2262  2313  365000      7301 W CHERYL DR  85345  Closed  6365681   
2263  2314  529000     4637 E GRANADA RD  85008  Closed  6354718   
2264  2315  460000       2016 W HOLLY ST  85009  Closed  6362564   

                   Subdivision  Year Built  Bedrooms  Bathrooms  Approx SQFT  
0     WEST PLAZA 6 LOT 614-787        1958         3        2.0       1302.0  
1               PAPAGO VILLAGE        1943         0        0.0       1358.0  
2                     SHALIMAR        1997         3        2.0       1505.0  
3      MARYVALE TERRACE NO. 49        1983         3        3.0       1514.0  
4               TU-DOR ESTATES        1971         4        2.0       1908.0  
...                        ...         ...       ...        ...          ...  
2260               BELLA TERRA        1981         3        2.0       2012.0  
2261        VILLAGES AT VERONA        2016         3        2.5       1499.0  
2262            SUNTOWN UNIT 2        1972         3        2.0       1581.0  
2263                RANCHO MIO        1953         3        2.0       1710.0  
2264                    VENICE        1953         3        2.0       1145.0  

[2265 rows x 11 columns]

In [5]:
merged_df=housing_df.merge(education_df, how='left', on='zip')
merged_df

id   Price               Address    zip  status      mls  \
0        1  427167   3231 W MARYLAND AVE  85017  Active  6395749   
1        2  400000      5109 E THOMAS RD  85018  Active  6243667   
2        3  399900     8020 W STELLA AVE  85303  Active  6384821   
3        4  349000       6944 W Verde LN  85033  Active  6395738   
4        5  419000   4105 W PASADENA AVE  85019  Active  6395732   
...    ...     ...                   ...    ...     ...      ...   
2260  2311  600000  3402 E CAROL ANN WAY  85032  Closed  6368329   
2261  2312  375000   739 E Constance WAY  85042  Closed  6358973   
2262  2313  365000      7301 W CHERYL DR  85345  Closed  6365681   
2263  2314  529000     4637 E GRANADA RD  85008  Closed  6354718   
2264  2315  460000       2016 W HOLLY ST  85009  Closed  6362564   

                   Subdivision  Year Built  Bedrooms  Bathrooms  Approx SQFT  \
0     WEST PLAZA 6 LOT 614-787        1958         3        2.0       1302.0   
1               PAPAGO VILLAGE        1943         0        0.0       1358.0   
2                     SHALIMAR        1997         3        2.0       1505.0   
3      MARYVALE TERRACE NO. 49        1983         3        3.0       1514.0   
4               TU-DOR ESTATES        1971         4        2.0       1908.0   
...                        ...         ...       ...        ...          ...   
2260               BELLA TERRA        1981         3        2.0       2012.0   
2261        VILLAGES AT VERONA        2016         3        2.5       1499.0   
2262            SUNTOWN UNIT 2        1972         3        2.0       1581.0   
2263                RANCHO MIO        1953         3        2.0       1710.0   
2264                    VENICE        1953         3        2.0       1145.0   

         Elem_School_District  Hightest_Rated_School  
0                    Alhambra                 100.04  
1                   Creighton                  75.80  
2                  Cartwright                  95.89  
3                  Cartwright                  95.89  
4                    Alhambra                 100.04  
...                       ...                    ...  
2260  Paradise Valley Unified                  99.97  
2261                Roosevelt                  76.54  
2262               Pendergast                  85.28  
2263                    Balsz                  81.79  
2264                   Murphy                  65.70  

[2265 rows x 13 columns]

In [6]:
new_housing_df=merged_df.drop(columns=['mls','Address','id','Subdivision','status','Elem_School_District'],axis=1)
new_housing_df

Price    zip  Year Built  Bedrooms  Bathrooms  Approx SQFT  \
0     427167  85017        1958         3        2.0       1302.0   
1     400000  85018        1943         0        0.0       1358.0   
2     399900  85303        1997         3        2.0       1505.0   
3     349000  85033        1983         3        3.0       1514.0   
4     419000  85019        1971         4        2.0       1908.0   
...      ...    ...         ...       ...        ...          ...   
2260  600000  85032        1981         3        2.0       2012.0   
2261  375000  85042        2016         3        2.5       1499.0   
2262  365000  85345        1972         3        2.0       1581.0   
2263  529000  85008        1953         3        2.0       1710.0   
2264  460000  85009        1953         3        2.0       1145.0   

      Hightest_Rated_School  
0                    100.04  
1                     75.80  
2                     95.89  
3                     95.89  
4                    100.04  
...                     ...  
2260                  99.97  
2261                  76.54  
2262                  85.28  
2263                  81.79  
2264                  65.70  

[2265 rows x 7 columns]

In [7]:
# Split our preprocessed data into our features and target arrays
y = new_housing_df["Price"].values
X = new_housing_df.drop(["Price"],axis=1).values

X

array([[8.5017e+04, 1.9580e+03, 3.0000e+00, 2.0000e+00, 1.3020e+03,
        1.0004e+02],
       [8.5018e+04, 1.9430e+03, 0.0000e+00, 0.0000e+00, 1.3580e+03,
        7.5800e+01],
       [8.5303e+04, 1.9970e+03, 3.0000e+00, 2.0000e+00, 1.5050e+03,
        9.5890e+01],
       ...,
       [8.5345e+04, 1.9720e+03, 3.0000e+00, 2.0000e+00, 1.5810e+03,
        8.5280e+01],
       [8.5008e+04, 1.9530e+03, 3.0000e+00, 2.0000e+00, 1.7100e+03,
        8.1790e+01],
       [8.5009e+04, 1.9530e+03, 3.0000e+00, 2.0000e+00, 1.1450e+03,
        6.5700e+01]])

In [8]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)


In [9]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [10]:
clf = RandomForestRegressor().fit(X_train, y_train)

In [11]:
print(f'Training Score: {clf.score(X_train, y_train)}')
print(f'Testing Score: {clf.score(X_test, y_test)}')

Training Score: 0.9608255265237181
Testing Score: 0.7113827441111356


In [12]:
predicted=clf.predict(X_test)
predicted

array([464024.        , 457506.        , 448990.16      , 791482.32      ,
       352008.74      , 657933.        , 518770.79      , 615398.95      ,
       364767.43      , 339800.61      , 477048.        , 452400.        ,
       419513.        , 354086.85      , 633099.5       , 493402.        ,
       550391.16666667, 673229.99      , 318762.55      , 628272.46      ,
       893734.        , 514182.        , 471570.        , 445934.63      ,
       734779.        , 348590.41666667, 714679.71      , 518599.89      ,
       405750.31333333, 651923.        , 389260.4       , 744119.99      ,
       379981.15      , 388376.5       , 538816.        , 604031.98      ,
       304697.93      , 354624.        , 349253.99      , 533623.        ,
       503972.2       , 710244.        , 640374.63      , 378715.99      ,
       798925.        , 352314.7       , 357499.45666667, 403506.5       ,
       496866.        , 378508.84      , 292153.23      , 337387.96      ,
       489976.89      , 4

In [13]:
comparison_df=pd.DataFrame(
{'actual':y_test,
 'predicted': predicted
})
comparison_df

actual  predicted
0    475900  464024.00
1    440000  457506.00
2    440000  448990.16
3    780000  791482.32
4    285000  352008.74
..      ...        ...
562  500000  435278.00
563  375000  359131.00
564  400000  424719.60
565  340000  347031.99
566  600000  637766.00

[567 rows x 2 columns]

In [14]:
pd.DataFrame(X_test)

0       1    2    3       4      5
0    85032.0  1972.0  3.0  2.0  1380.0  99.97
1    85041.0  2013.0  4.0  2.0  1681.0  76.54
2    85303.0  2002.0  3.0  2.5  1866.0  95.89
3    85020.0  1993.0  4.0  2.5  2517.0  97.13
4    85041.0  1949.0  4.0  2.0  1288.0  76.54
..       ...     ...  ...  ...     ...    ...
562  85006.0  1939.0  2.0  1.0   942.0  94.44
563  85043.0  1976.0  3.0  1.0  1192.0  76.86
564  85032.0  1974.0  3.0  2.0  1144.0  99.97
565  85033.0  2000.0  2.0  2.0   919.0  95.89
566  85013.0  1947.0  3.0  2.0  1455.0  72.93

[567 rows x 6 columns]

In [15]:
to_predict = [[85032.0, 2010, 3.0, 2.0, 1380.0, 99.97]]

In [16]:
clf.predict(to_predict)

array([461503.16])

In [17]:
clf.feature_importances_

array([0.17902359, 0.08946133, 0.01609674, 0.02964883, 0.45861735,
       0.22715216])

In [18]:
df=new_housing_df.drop('Price',axis=1)
df

zip  Year Built  Bedrooms  Bathrooms  Approx SQFT  \
0     85017        1958         3        2.0       1302.0   
1     85018        1943         0        0.0       1358.0   
2     85303        1997         3        2.0       1505.0   
3     85033        1983         3        3.0       1514.0   
4     85019        1971         4        2.0       1908.0   
...     ...         ...       ...        ...          ...   
2260  85032        1981         3        2.0       2012.0   
2261  85042        2016         3        2.5       1499.0   
2262  85345        1972         3        2.0       1581.0   
2263  85008        1953         3        2.0       1710.0   
2264  85009        1953         3        2.0       1145.0   

      Hightest_Rated_School  
0                    100.04  
1                     75.80  
2                     95.89  
3                     95.89  
4                    100.04  
...                     ...  
2260                  99.97  
2261                  76.54  
2262                  85.28  
2263                  81.79  
2264                  65.70  

[2265 rows x 6 columns]